### ISSUE TITLE
First argument in get_sample_info(f, vcf)

### ISSUE THREAD

**Issue by ebogey** [tomsasani/denovo_scripts#1]
What is it you are passing with f? I don't think I see it any where else so I am unsure about what it is doing.

**Comment by tomsasani** [comment]
My first issue!

`f` is just an arbitrary argument name. In the main `de_novo.py` script (line 28), you can see that I pass `ped.families[fam]` into `get_sample_info` as `f`.

**Comment by ebogey** [comment]
Ah, I see it now. Way to handle the issue.
